"""create rental requests table

Revision ID: 1f7df1eb9baf
Revises: 75cc71cee4e1
Create Date: 2026-08-10 21:44:41.860824
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f7df1eb9baf'
down_revision: Union[str, None] = '75cc71cee4e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'accepted', 'rejected', 'cancelled', 'completed')", name='ck_rental_requests_status'),
    sa.CheckConstraint('start_date <= end_date', name='ck_rental_requests_dates'),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_requests_borrower_id'), 'rental_requests', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_rental_requests_equipment_id'), 'rental_requests', ['equipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_requests_equipment_id'), table_name='rental_requests')
    op.drop_index(op.f('ix_rental_requests_borrower_id'), table_name='rental_requests')
    op.drop_table('rental_requests')
    # ### end Alembic commands ###
