"""add pickup location to equipment

Revision ID: 2ca36d24e6f1
Revises: 9c4b7d8e0f2b
Create Date: 2026-08-14 16:54:28.968571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ca36d24e6f1'
down_revision: Union[str, None] = '9c4b7d8e0f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('pickup_location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'pickup_location')
    # ### end Alembic commands ###
