"""add_image_url_to_equipment

Revision ID: 9a8135a5fdb8
Revises: d6fa4974832d
Create Date: 2026-08-12 18:57:10.412826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a8135a5fdb8'
down_revision: Union[str, None] = 'd6fa4974832d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'image_url')
    # ### end Alembic commands ###
