"""add_reviews_and_multiple_images

Revision ID: fcfcb90973ac
Revises: 9a8135a5fdb8
Create Date: 2026-08-12 19:33:55.652421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcfcb90973ac'
down_revision: Union[str, None] = '9a8135a5fdb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_equipment_id'), 'reviews', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    op.add_column('equipment', sa.Column('image_urls', sa.JSON(), server_default='[]', nullable=False))
    op.drop_column('equipment', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('equipment', 'image_urls')
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_equipment_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
